### ISSUE TITLE
"Unexpected role in multipolygon" makes graph building fail using OSM extracts since latest merges

### ISSUE THREAD

**Issue by kalon33** [HSLdevcom/OpenTripPlanner#82]
Since PR #79 merging, I'm not able to build graphs anymore, due to a "expected role in multipolygon" error.

Please fix!

**Comment by kalon33** [comment]
@hannesj @samuliheljo any idea of what may cause that bug in the commits you merged? With the same data, I didn't triggered that error before, and I use standard OSM extract from geofabrik...

**Comment by samuliheljo** [comment]
Sorry, we have no ideas...

You should try with upstream OTP.

-Samuli


--
Samuli Heljo
+358 50 3537299

**Comment by kalon33** [comment]
@samuliheljo I found the problem, apparently there's something wrong in OSM data around Paris, but I don't know where (or how to find this), and I don't understand why OTP doesn't simply ignore the error.

If you try to make a graph with this OSM extract http://download.geofabrik.de/europe/france/ile-de-france-latest.osm.pbf , you should be able to reproduce. BTW, I'm nearly sure that it didn't happen before with july extracts, while it does now happen.

Thanks for your help.

Here is the full error I get:

`13:28:41.081 WARN (OSMDatabase.java:660) Unexpected role  in multipolygon
13:28:41.272 WARN (OSMDatabase.java:660) Unexpected role  in multipolygon
Exception in thread "main" java.lang.IllegalStateException: error loading OSM from path pdx/paris/ile-de-france-latest.osm.pbf
        at org.opentripplanner.openstreetmap.impl.AnyFileBasedOpenStreetMapProviderImpl.readOSM(AnyFileBasedOpenStreetMapProviderImpl.java:48)
        at org.opentripplanner.graph_builder.module.osm.OpenStreetMapModule.buildGraph(OpenStreetMapModule.java:165)
        at org.opentripplanner.graph_builder.GraphBuilder.run(GraphBuilder.java:157)
        at org.opentripplanner.standalone.OTPMain.run(OTPMain.java:111)
        at org.opentripplanner.standalone.OTPMain.main(OTPMain.java:86)
Caused by: java.lang.IllegalStateException: error loading OSM from path pdx/paris/ile-de-france-latest.osm.pbf
        at org.opentripplanner.openstreetmap.impl.BinaryFileBasedOpenStreetMapProviderImpl.readOSM(BinaryFileBasedOpenStreetMapProviderImpl.java:58)
        at org.opentripplanner.openstreetmap.impl.AnyFileBasedOpenStreetMapProviderImpl.readOSM(AnyFileBasedOpenStreetMapProviderImpl.java:41)
        ... 4 more
Caused by: org.opentripplanner.graph_builder.module.osm.Ring$RingConstructionException
        at org.opentripplanner.graph_builder.module.osm.Ring.toJtsPolygon(Ring.java:97)
        at org.opentripplanner.graph_builder.module.osm.Area.toJTSMultiPolygon(Area.java:97)
        at org.opentripplanner.graph_builder.module.osm.Area.<init>(Area.java:90)
        at org.opentripplanner.graph_builder.module.osm.OSMDatabase.processSingleWayAreas(OSMDatabase.java:610)
        at org.opentripplanner.graph_builder.module.osm.OSMDatabase.doneThirdPhaseNodes(OSMDatabase.java:307)
        at org.opentripplanner.openstreetmap.impl.BinaryFileBasedOpenStreetMapProviderImpl.readOSM(BinaryFileBasedOpenStreetMapProviderImpl.java:56)
        ... 5 more
`

**Comment by samuliheljo** [comment]
Intresting... You might want to report this to opentripplanner upstream. I'm closing this from our fork.

**Comment by kalon33** [comment]
Issue reported upstream as https://github.com/opentripplanner/OpenTripPlanner/issues/2319 

Thanks @samuliheljo
