### ISSUE TITLE
TimedExecutorServiceExecutionStrategy makes Lucene indexing failing

### ISSUE THREAD

**Issue by kalon33** [HSLdevcom/OpenTripPlanner#95]
Since PR #94 merging, Lucene indexing is failing:

`19:42:27.156 INFO (LuceneIndex.java:148) Starting background Lucene indexing.
19:42:38.224 INFO (ExecutionStrategy.java:42) Exception while fetching data
java.lang.RuntimeException: Lucene indexing failed.
        at org.opentripplanner.common.LuceneIndex.index(LuceneIndex.java:100) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at org.opentripplanner.common.LuceneIndex.access$200(LuceneIndex.java:47) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at org.opentripplanner.common.LuceneIndex$BackgroundIndexer.run(LuceneIndex.java:149) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at org.opentripplanner.common.LuceneIndex.<init>(LuceneIndex.java:68) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at org.opentripplanner.routing.graph.GraphIndex.getLuceneIndex(GraphIndex.java:449) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at org.opentripplanner.index.IndexGraphQLSchema.lambda$new$242(IndexGraphQLSchema.java:1943) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:40) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at org.opentripplanner.index.TimedExecutorServiceExecutionStrategy.lambda$execute$332(TimedExecutorServiceExecutionStrategy.java:57) [otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_66-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66-internal]
Caused by: java.nio.channels.ClosedByInterruptException: null
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202) ~[na:1.8.0_66-internal]
        at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:970) ~[na:1.8.0_66-internal]
        at org.apache.lucene.store.MMapDirectory.map(MMapDirectory.java:283) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at org.apache.lucene.store.MMapDirectory$MMapIndexInput.<init>(MMapDirectory.java:228) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at org.apache.lucene.store.MMapDirectory.openInput(MMapDirectory.java:195) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at org.apache.lucene.store.Directory.copy(Directory.java:185) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at org.apache.lucene.store.TrackingDirectoryWrapper.copy(TrackingDirectoryWrapper.java:50) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at org.apache.lucene.index.IndexWriter.createCompoundFile(IndexWriter.java:4672) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at org.apache.lucene.index.DocumentsWriterPerThread.sealFlushedSegment(DocumentsWriterPerThread.java:535) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:502) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:508) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at org.apache.lucene.index.DocumentsWriter.postUpdate(DocumentsWriter.java:380) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:472) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1534) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1204) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1185) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at org.opentripplanner.common.LuceneIndex.addStop(LuceneIndex.java:114) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        at org.opentripplanner.common.LuceneIndex.index(LuceneIndex.java:85) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
        ... 11 common frames omitted`

Please fix :)

**Comment by samuliheljo** [comment]
I'll add question to here as well:

Could you try:
- removing lucene index folder from your machine (its location should be
visible in stacktrace you are seeing); and
- rebuilding otp; and
- rebuilding graph; and
- see if it works now

**Comment by kalon33** [comment]
I already tried, but unfortunately it didn't fixed it. 


----- Original Message -----

**Comment by samuliheljo** [comment]
Are you still having issues with this?

**Comment by kalon33** [comment]
No, I don't remember how I make it working but it doesn't happen anymore. Thanks!

**Comment by samuliheljo** [comment]
Ok, great!
